<!doctype html>
<html>
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>RAST source code scanning summary</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<link rel="stylesheet" href="css/bootstrap.min.css">
<script src="js/jquery-2.1.4.min.js" type="text/javascript"></script>
<script src="js/bootstrap.min.js"></script>
<link href="css/jquerysctipttop.css" rel="stylesheet" type="text/css">
<!-- INCLUDES -->
<link rel="stylesheet" href="css/bootstrap-table-expandable.css">
<script src="js/bootstrap-table-expandable.js"></script>
<style>
h2 {color: #7c795d; font-family: 'Trocchi', serif; font-size: 45px; font-weight: normal; line-height: 48px; margin: 0; text-align: center;   }
table.repo_table {
color:#fff;
font-family:Helvetica,Arial,sans-serif;
border-collapse: collapse;
padding:0 3px;
border-radius: 5px;
margin: 25px auto;
}

table.repo_table td, table.repo_table th {
height:30px;
transition:all 1.5s;
text-align:center;
padding: 5px 40px;
border: 2px solid #000;
width: 200px;
}

table.repo_table th {
background:#000;
font-weight:700;
}

table.repo_table tr td {
background:#fff;
color:#000;
}

table.repo_table tr td:hover {
background:#666;
color:#FFF;
font-weight:bold;
}
</style>
</head>
<body>



<div class="container">
<br>
<br>
<br>
<br>
  <h2>RAST Summary</h2>

<!--  <p><strong>Note:</strong> The <strong>data-parent</strong> attribute makes sure that all collapsible elements under the specified parent will be closed when one of the collapsible item is shown.</p>
<p>Demo for <a href="http://www.jankoatwarpspeed.com/post/2009/07/19/Expand-table-rows-with-jQuery-jExpand-plugin.aspx">Expand table rows with jQuery - jExpand plugin</a></p> -->

<table class="repo_table">
    <thead>
        <tr>
            <th>Rule Name</th>
            <th>Total Violations</th>
            
        </tr>
    </thead>
    <tbody>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/DCL00-J.+Prevent+class+initialization+cycles" target="_blank"> DCL00J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/DCL01-J.+Do+not+reuse+public+identifiers+from+the+Java+Standard+Library" target="_blank"> DCL01-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/DCL02-J.+Do+not+modify+the+collection%27s+elements+during+an+enhanced+for+statement" target="_blank"> DCL02-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/EXP02-J.+Do+not+use+the+Object.equals%28%29+method+to+compare+two+arrays" target="_blank"> EXP02-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/ERR02-J.+Prevent+exceptions+while+logging+data" target="_blank"> ERR02-J</a></td>
<td>8</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/ERR04-J.+Do+not+complete+abruptly+from+a+finally+block" target="_blank"> ERR04-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J</a></td>
<td>13</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/ERR07-J.+Do+not+throw+RuntimeException%2C+Exception%2C+or+Throwable" target="_blank"> ERR07-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/ERR02-J.+Prevent+exceptions+while+logging+data" target="_blank"> ERR08-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/FIO02-J.+Detect+and+handle+file-related+errors" target="_blank"> FIO02-J</a></td>
<td>3</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/LCK01-J.+Do+not+synchronize+on+objects+that+may+be+reused" target="_blank"> LCK01-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/pages/viewpage.action?pageId=43647087" target="_blank"> LCK02-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/MET09-J.+Classes+that+define+an+equals%28%29+method+must+also+define+a+hashCode%28%29+method" target="_blank"> MET09-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/MSC00-J.+Use+SSLSocket+rather+than+Socket+for+secure+data+exchange" target="_blank"> MSC00-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/MSC01-J.+Do+not+use+an+empty+infinite+loop" target="_blank"> MSC01-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/MSC02-J.+Generate+strong+random+numbers" target="_blank"> MSC02-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/NUM07-J.+Do+not+attempt+comparisons+with+NaN" target="_blank"> NUM07-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/NUM09-J.+Do+not+use+floating-point+variables+as+loop+counters" target="_blank"> NUM09-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/NUM10-J.+Do+not+construct+BigDecimal+objects+from+floating-point+literals" target="_blank"> NUM10-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank"> OBJ09-J</a></td>
<td>0</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ10-J.+Do+not+use+public+static+nonfinal+fields" target="_blank"> OBJ10-J</a></td>
<td>3</td>
 </tr>
<tr>
<td><a href="https://www.securecoding.cert.org/confluence/display/java/SER05-J.+Do+not+serialize+instances+of+inner+classes" target="_blank"> SER05-J</a></td>
<td>0</td>
 </tr>

 </tbody>
    </table> 
<br>
<hr noshade>
<br>
<h4 style="color:#660000;">Total 5 directories searched and 17 files scanned. Out of the above rules, 27 CERT violations are reported </h4>
<br>
<hr noshade>
<br>
<div style="text-align:center">  
     <button class="btn" data-toggle="collapse" data-target="#demo">View Detailed Report</button>
</div> 
<div id="demo" class="collapse">
<h4>Following files have secure coding violations </h4>
  <div class="panel-group" id="accordion">
    <div class="panel panel-default">
  
        <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc1">FmFavoriteEditDialog.java</a>
        </h4>
      </div>
      <div id="Loc1" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/dialogs/FmFavoriteEditDialog.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/dialogs/FmFavoriteEditDialog.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>78</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">78 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc2">FmSaveDialog.java</a>
        </h4>
      </div>
      <div id="Loc2" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/dialogs/FmSaveDialog.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/dialogs/FmSaveDialog.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>95</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">95 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>FIO02-J</td>
		<td>CERT</td>
		<td>244</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>FIO02-J. Detect and handle file-related errors</h4>
     <p>Java's file-manipulation methods often indicate failure with a return value instead of throwing an exception. Consequently, programs that ignore the return values from file operations often fail to detect that those operations have failed. Java programs must check the return values of methods that perform file I/O.</p>
        
        <p>In the given program line number <span style="color: red">244 </span> code block <span style="color: red">needToDelete.delete();
 </span> trying to delete file without detect and handle file-related errors </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example attempts to delete a specified file but gives no indication of its success.  </p>
 <pre><code class="language-java"> 
 class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
	file.delete();
}
	}
	
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution checks the return value of delete()</p>
 <pre><code class="language-java"> class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
if (!file.delete()) {
  System.out.println("Deletion failed");
}
	}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/FIO02-J.+Detect+and+handle+file-related+errors" target="_blank"> FIO02-J. Detect and handle file-related errors</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/cplusplus/FIO04-CPP.+Detect+and+handle+input+and+output+errors" target="_blank"> FIO04-CPP. Detect and handle input and output errors</a></li>
          </ul></td>  </tr>
	  <tr>
		<td>FIO02-J</td>
		<td>CERT</td>
		<td>244</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>FIO02-J. Detect and handle file-related errors</h4>
     <p>Java's file-manipulation methods often indicate failure with a return value instead of throwing an exception. Consequently, programs that ignore the return values from file operations often fail to detect that those operations have failed. Java programs must check the return values of methods that perform file I/O.</p>
        
        <p>In the given program line number <span style="color: red">244 </span> code block <span style="color: red">needToDelete.delete();
 </span> trying to delete file without detect and handle file-related errors </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example attempts to delete a specified file but gives no indication of its success.  </p>
 <pre><code class="language-java"> 
 class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
	file.delete();
}
	}
	
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution checks the return value of delete()</p>
 <pre><code class="language-java"> class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
if (!file.delete()) {
  System.out.println("Deletion failed");
}
	}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/FIO02-J.+Detect+and+handle+file-related+errors" target="_blank"> FIO02-J. Detect and handle file-related errors</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/cplusplus/FIO04-CPP.+Detect+and+handle+input+and+output+errors" target="_blank"> FIO04-CPP. Detect and handle input and output errors</a></li>
          </ul></td>  </tr>
	  <tr>
		<td>FIO02-J</td>
		<td>CERT</td>
		<td>244</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>FIO02-J. Detect and handle file-related errors</h4>
     <p>Java's file-manipulation methods often indicate failure with a return value instead of throwing an exception. Consequently, programs that ignore the return values from file operations often fail to detect that those operations have failed. Java programs must check the return values of methods that perform file I/O.</p>
        
        <p>In the given program line number <span style="color: red">244 </span> code block <span style="color: red">needToDelete.delete();
 </span> trying to delete file without detect and handle file-related errors </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example attempts to delete a specified file but gives no indication of its success.  </p>
 <pre><code class="language-java"> 
 class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
	file.delete();
}
	}
	
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution checks the return value of delete()</p>
 <pre><code class="language-java"> class FileDelete {
	public static void main(String args[]){
		File file = new File("file");
if (!file.delete()) {
  System.out.println("Deletion failed");
}
	}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/FIO02-J.+Detect+and+handle+file-related+errors" target="_blank"> FIO02-J. Detect and handle file-related errors</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/cplusplus/FIO04-CPP.+Detect+and+handle+input+and+output+errors" target="_blank"> FIO04-CPP. Detect and handle input and output errors</a></li>
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc3">FmFavoriteActivity.java</a>
        </h4>
      </div>
      <div id="Loc3" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmFavoriteActivity.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmFavoriteActivity.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>137</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">137 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc5">FmMainActivity.java</a>
        </h4>
      </div>
      <div id="Loc5" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmMainActivity.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmMainActivity.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>493</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">493 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>495</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">495 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>497</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">497 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>626</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">626 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc8">FmRecordActivity.java</a>
        </h4>
      </div>
      <div id="Loc8" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmRecordActivity.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmRecordActivity.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>160</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">160 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc9">FmRecorder.java</a>
        </h4>
      </div>
      <div id="Loc9" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmRecorder.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmRecorder.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>143</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">143 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>442</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">442 </span> A method invocation <span style="color: red">playlistCursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>492</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">492 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>516</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">516 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>534</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">534 </span> A method invocation <span style="color: red">mRecorder.release() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc10">FmService.java</a>
        </h4>
      </div>
      <div id="Loc10" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmService.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmService.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>523</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">523 </span> A method invocation <span style="color: red">mAudioTrack.stop() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR02-J</td>
		<td>CERT</td>
		<td>1592</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR02-J. Prevent exceptions while logging data</h4>
     <p>When logging a message there are several important requirements which must be fulfilled:
<ul>
            <li>The user must be able to easily retrieve the logs</li>
            <li>The format of all logged message must be uniform to allow the user to easily read the log</li>
            <li>Logged data must actually be recorded</li>
            <li>Sensitive data must only be logged securely            </li></ul>
If a program directly writes to the standard outputs, there is absolutely no way to comply with those requirements. That's why defining and using a dedicated logger is highly recommended.</p>
        
        <p>In the given program line number <span style="color: red">1592 </span> code block <span style="color: red">e.printStackTrace() </span> trying to </p> 
       <span style="color: #660000">  <h4>Non-compliant Solution</h4></span> 
<p> his noncompliant code example writes a critical security exception to the standard error stream.Writing such exceptions to the standard error stream is inadequate for logging purposes. First, the standard error stream may be exhausted or closed, preventing recording of subsequent exceptions. Second, the trust level of the standard error stream may be insufficient for recording certain security-critical exceptions or errors without leaking sensitive information. If an I/O error were to occur while writing the security exception, the catch block would throw an IOException and the critical security exception would be lost. Finally, an attacker may disguise the exception so that it occurs with several other innocuous exceptions.
Using Console.printf(), System.out.print*(), or Throwable.printStackTrace() to output a security exception also constitutes a violation of this rule.</p>
 <pre><code class="language-java"> 
try {
  // ...
} catch (SecurityException se) {
  System.err.println(se);
  // Recover from exception
}
 </code></pre>
<span style="color: #00b33c"><h4>Compliant Solution</h4></span>
<p> This compliant solution uses java.util.logging.Logger, the default logging API provided by JDK 1.4 and later. Use of other compliant logging mechanisms, such as log4j, is also permitted.</p>
 <pre><code class="language-java"> try {
  // ...
} catch(SecurityException se) {
  logger.log(Level.SEVERE, se);
  // Recover from exception
}</code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/OBJ09-J.+Compare+classes+and+not+class+names" target="_blank">ERR02-J. Prevent exceptions while logging data</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://issues.apache.org/jira/browse/HARMONY-5981" target="_blank"> HARMONY-5981  </a> </li>
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>1757</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">1757 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>2296</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">2296 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
  <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">
          <a data-toggle="collapse" data-parent="#accordion" href="#Loc11">FmStation.java</a>
        </h4>
      </div>
      <div id="Loc11" class="panel-collapse collapse collapse">
        <div class="panel-body"> <table class="table table-hover table-expandable table-striped">
    <thead>
 <p>Location :<a href="/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmStation.java">/media/rahul/Education/Project/src/M/Sources/packages/apps/FMRadio/src/com/android/fmradio/FmStation.java</a></p>

      <tr>
        <th>Rule</th>
        <th>Standard</th>
        <th>Line number</th>
        
      </tr>
    </thead>
    <tbody>
      
      
   	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>199</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">199 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>259</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">259 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>288</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">288 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
	  <tr>
		<td>ERR05-J</td>
		<td>CERT</td>
		<td>349</td>
		<td><!--$001violation$001--></td>
	      </tr>
      

<tr>

      
        <td colspan="5">
 <h4>ERR05-J. Do not let checked exceptions escape from a finally block</h4>
     <p>Methods invoked from within a finally block can throw an exception. Failure to catch and handle such exceptions results in the abrupt termination of the entire try block. Abrupt termination causes any exception thrown in the try block to be lost, preventing any possible recovery method from handling that specific problem. </p>
        
        <p>In the given program line number <span style="color: red">349 </span> A method invocation <span style="color: red">cursor.close() </span> is present inside a finally block without a try-catch block </p> 
        <span style="color: #660000">  <h4>Non-compliant Solution</h4></span>
<p> This noncompliant code example contains a finally block that closes the reader object. The programmer incorrectly assumes that the statements in the finally block cannot throw exceptions and consequently fails to appropriately handle any exception that may arise. </p>
 <pre><code class="language-java"> 
 try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        reader.close();
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
 </code></pre>
<span style="color:#00b33c"><h4>Compliant Solution</h4></span>
<p>  This compliant solution encloses the close() method invocation in a try-catch block of its own within the finally block. Consequently, the potential IOException can be handled without allowing it to propagate further.t</p>
 <pre><code class="language-java"> 
  try {
      BufferedReader reader =
          new BufferedReader(new FileReader(some_file));
      try {
        // Do operations
      } finally {
        try {
          reader.close();
        } catch (IOException ie) {
          // Forward to handler
        }
        // ... Other cleanup code ...
      }
    } catch (IOException x) {
      // Forward to handler
    }
    </code></pre>
<h4>Additional information</h4>
          <ul>
            <li><a href="https://www.securecoding.cert.org/confluence/display/java/ERR05-J.+Do+not+let+checked+exceptions+escape+from+a+finally+block" target="_blank"> ERR05-J. Do not let checked exceptions escape from a finally block</a></li>
          </ul> 
          <h4>Related Guidelines</h4>
          <ul>
            <li><a href="http://cwe.mitre.org/data/definitions/703.html" target="_blank"> CWE-703,</a> Improper Check or Handling of Exceptional Conditions</li>
          <li><a href="http://cwe.mitre.org/data/definitions/248.html" target="_blank"> CWE-248,</a> Uncaught Exception</li>
          
          </ul></td>  </tr>
<!--$newtableblockattachhere-->
    </tbody>
  </table></div>
      </div>
    </div>

    
 
 <!--$newfileblockattachhere-->
    
  </div> 
</div>
</div>   
<br>
<br>
<br>
<br>
<br>
</body>
</html>

